server:
  image: "quay.io/keboola/docs-example-logging-mock-server:master"
  ports:
    - 12202:12202/udp
  environment:
    SERVER_TYPE: udp
client:
  image: "quay.io/keboola/docs-example-logging-js:master"
  links:
    - server:log-server
  environment:
    KBC_LOGGER_ADDR: log-server
    KBC_LOGGER_PORT: 12202
